schema {
  query: Query
  mutation: Mutation
    subscription: Subscription
}

type Mutation {
    stripePaymentLink(data: String!): StripePaymentLinkResponse @aws_iam @aws_api_key

    batchUploadProducts: String
    createStripeProducts:String
}
type Query {
    getProduct(id:String!):Product!

}

type Subscription {
    onStripePaymentLinkResponse: StripePaymentLinkResponse
		@aws_subscribe(mutations: ["stripePaymentLink"])

}
type StripePaymentLinkResponse @aws_iam @aws_api_key{

	data: AWSJSON!
}


type Product {
    productId: String!
    category: String!
    createdDate: String!
    description: String!
    modifiedDate: String!
    name: String!
    package: Package!
    pictures: [String!]!
    price: Int!
    tags: [String!]!
}

type Package {
    height: Int!
    length: Int!
    weight: Int!
    width: Int!
}



input ProductInput {
    productId: String!
    category: String!
    createdDate: String!
    description: String!
    modifiedDate: String!
    name: String!
    package: PackageInput!
    pictures: [String!]!
    price: Int!
    tags: [String!]!
}

input PackageInput {
    height: Int!
    length: Int!
    weight: Int!
    width: Int!
}
